### ISSUE TITLE
Is possible a version without newArch?

### ISSUE THREAD

**Issue by AlexCernik** [pushpender-singh-ap/react-native-scanner#12]
Hi, are you planning to deploy a new version without newArch? Using newArch causes strange behavior in several other packages. Greetings

**Comment by pushpender-singh-ap** [comment]
Hi @AlexCernik, I will try to create this package without newArch.

**Comment by pushpender-singh-ap** [comment]
Hi @AlexCernik, That sounds fantastic! I'll give it a go shortly. Currently tied up with a few tasks, so if you have the availability, please feel free to implement it and initiate the pull request. Your efforts are much appreciated!

**Comment by pushpender-singh-ap** [comment]
Due to my busy schedule, I currently lack the time to address these issues. If you discover any solutions, kindly submit a pull request. Thank you for your understanding.

**Comment by pushpender-singh-ap** [comment]
@AlexCernik We've added a flashlight feature for Android! To check it out, please update to the latest beta version (v1.2.0-beta.1).
