### ISSUE TITLE
Supporting both old & new architectures

### ISSUE THREAD

**Issue by tamas-toth** [pushpender-singh-ap/react-native-scanner#13]
Hi,

Currently this component supports only the new architecture. 
Can you please add old architecture support as well?
As I can see it shouldn't be a big deal...you can read more about [here](https://reactnative.dev/docs/the-new-architecture/backward-compatibility-fabric-components).

**Comment by pushpender-singh-ap** [comment]
@tamas-toth Due to my busy schedule, I currently lack the time to address these issues. If you discover any solutions, kindly submit a pull request. Thank you for your understanding.
