### ISSUE TITLE
Native Module do not release memory on RN component unmount

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [pushpender-singh-ap/react-native-scanner#14]
@pushpender-singh-ap  I have observed that the component do not get deallocated from memory on unmount of RN component, can you please check on this issue.

**Comment by ravindraguptacapgemini** [comment]
@pushpender-singh-ap have you got a chance to check this issue?

**Comment by pushpender-singh-ap** [comment]
@ravindraguptacapgemini Due to my busy schedule, I currently lack the time to address these issues. If you discover any solutions, kindly submit a pull request. Thank you for your understanding.

**Comment by daviCamarinha** [comment]
Some solution for this issue?

**Comment by pushpender-singh-ap** [comment]
@daviCamarinha I think you can add the custom prop for closing the scanner.
