### ISSUE TITLE
ReactNativeScannerView" was not found in the UIManager

### ISSUE THREAD

**Issue by deeps0903** [pushpender-singh-ap/react-native-scanner#15]
Invariant Violation: requireNativeComponent: "ReactNativeScannerView" was not found in the UIManager.

**Comment by pushpender-singh-ap** [comment]
@deeps0903 

1. React native version
2. @pushpendersingh/react-native-scanner version
3. Are you using newArch?
4. Please share the "npx react-native info" command output.

**Comment by deeps0903** [comment]
@pushpender-singh-ap 
React native version -> "0.64.4"
@pushpendersingh/react-native-scanner version -> "^1.1.0-beta.2"
Are you using newArch? -> enable new architecture for android (by addig newArchEnabled=true in gradle.properties )
Please share the "npx react-native info" command output. -> Not Found :- 
![Uploading Screenshot 2024-01-02 at 8.10.59 PM.png…]()

**Comment by pushpender-singh-ap** [comment]
In React Native, the introduction of 'newArch' came with version 0.68. However, your current version is 0.64. To leverage the new architecture, it's crucial to upgrade React Native to a minimum of version 0.70. Following the upgrade, ensure to enable the 'newArch' for both platforms. Once this is accomplished, you can seamlessly incorporate the functionality of the '@pushpendersingh/react-native-scanner' library by installing the stable 1.0.2 version of the library

**Comment by deeps0903** [comment]
okay! Thanks

**Comment by xiongxiongjiang** [comment]
i'm using 0.72.0 and newArchEnabled=true，still report “Possible Unhandled Promise Rejection (id: 0):
Invariant Violation: requireNativeComponent: "ReactNativeScannerView" was not found in the UIManager.
Invariant Violation: requireNativeComponent: "ReactNativeScannerView" was not found in the UIManager.”

**Comment by pushpender-singh-ap** [comment]
@xiongxiongjiang Would you mind sharing a sample project with us? It would be immensely helpful for us to accurately diagnose and address the issue at hand.
