### ISSUE TITLE
[Android] Build failed using React native 0.74.1 Compilation regarding Kotlin

### ISSUE THREAD

**Issue by naheedsa** [pushpender-singh-ap/react-native-scanner#17]
![Screenshot_20240504_161535](https://github.com/pushpender-singh-ap/react-native-scanner/assets/97088153/45db3ebc-8879-44a3-b41b-3bbc207bc310)

**Comment by pushpender-singh-ap** [comment]
Hi @naheedsa 
1. What is your environment device? (MacOS, Linux, Window)
2. Can you please share the test repo?

**Comment by naheedsa** [comment]
> Hi @naheedsa
> 
> 1. What is your environment device? (MacOS, Linux, Window)
> 2. Can you please share the test repo?

1. Using KDE Neon Linux, building for android
2. Let me check it, we probably need to add your ssh key to access the repo

**Comment by pushpender-singh-ap** [comment]
Hey @naheedsa , just a heads-up: React Native version 0.74 introduced some significant changes to its new architecture. If it's convenient for you, could you possibly stick to using v0.73 for now?

**Comment by pushpender-singh-ap** [comment]
This issue has been fixed please install **v1.1.0**

**Comment by naheedsa** [comment]
Getting this error now: tried with both 1.1.0 and 1.2.0 react native version 0.73.8


BUILD FAILED in 7s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/stellarmate/Projects/test/new/stellarmateapp2/node_modules/@react-native-async-storage/async-storage/android/src/javaPackage/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/stellarmate/Projects/test/new/stellarmateapp2/node_modules/@react-native-camera-roll/camera-roll/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollPackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
e: file:///home/stellarmate/Projects/test/new/stellarmateapp2/node_modules/@pushpendersingh/react-native-scanner/android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerViewManager.kt:9:40 Unresolved reference: ReactNativeScannerViewManagerInterface
e: file:///home/stellarmate/Projects/test/new/stellarmateapp2/node_modules/@pushpendersingh/react-native-scanner/android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerViewManager.kt:10:40 Unresolved reference: ReactNativeScannerViewManagerDelegate
e: file:///home/stellarmate/Projects/test/new/stellarmateapp2/node_modules/@pushpendersingh/react-native-scanner/android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerViewManager.kt:14:48 Unresolved reference: ReactNativeScannerViewManagerInterface
e: file:///home/stellarmate/Projects/test/new/stellarmateapp2/node_modules/@pushpendersingh/react-native-scanner/android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerViewManager.kt:19:17 Unresolved reference: ReactNativeScannerViewManagerDelegate
e: file:///home/stellarmate/Projects/test/new/stellarmateapp2/node_modules/@pushpendersingh/react-native-scanner/android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerViewManager.kt:30:3 'enableFlashlight' overrides nothing
e: file:///home/stellarmate/Projects/test/new/stellarmateapp2/node_modules/@pushpendersingh/react-native-scanner/android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerViewManager.kt:34:3 'disableFlashlight' overrides nothing
e: file:///home/stellarmate/Projects/test/new/stellarmateapp2/node_modules/@pushpendersingh/react-native-scanner/android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerViewManager.kt:38:3 'releaseCamera' overrides nothing
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details. FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':pushpendersingh_react-native-scanner:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log

**Comment by pushpender-singh-ap** [comment]
@naheedsa Are you using new architecture?

**Comment by pushpender-singh-ap** [comment]
@naheedsa Could you please share the example repository? It would greatly assist in debugging the error.
