### ISSUE TITLE
Native Component not getting released from memory

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [pushpender-singh-ap/react-native-scanner#31]
### Ask your Question
Hi, I have seen that when the React Native component for ReactNativeScannerView deallocated the related native component do not deallocate.
Due to this if you try to use the Scanner next time, the scanner do not work at all, please check this once when you have time. we can discuss this more.

**Comment by pushpender-singh-ap** [comment]
Hi @ravindraguptacapgemini 

Thank you for opening the issue. Could you please share a test repository or sample project where this issue occurs? This will help me test and debug the problem, as I am not currently using this library in any of my projects. Additionally, please provide any debugging steps or insights you have already tried to help me understand the issue better.

Thanks & Regards
Pushpender Singh

**Comment by ravindraguptacapgemini** [comment]
Just try hide/show the ReactNativeScannerView in any component/screen and you will get the issue.

**Comment by danish5454** [comment]
@pushpender-singh-ap  getting same issue...
After scanning the barcode, navigate to a different screen and then come back to the camera screen again. The scanner is not working.....

**Comment by pushpender-singh-ap** [comment]
Hi buddy @danish5454 - you are using the releaseCamera command?

**Comment by danish5454** [comment]
No @pushpender-singh-ap I'm not using any **command** after scanning the barcode navigating to a different screen. Coming back to the scanning screen camera not working..

**Comment by pushpender-singh-ap** [comment]
@danish5454 is this thing only happen in iOS only or it's happen on both platform?

**Comment by crzycoder** [comment]
@pushpender-singh-ap I tested it on Android

**Comment by pushpender-singh-ap** [comment]
@danish5454 Currently, I am aware that this issue is only affecting the iOS environment. I will investigate this matter in both environments to determine the root cause, Thanks for the help.

**Comment by ravindraguptacapgemini** [comment]
@pushpender-singh-ap you may check for code difference with my code https://github.com/IntelexTechnologies/react-native-scanner

**Comment by pushpender-singh-ap** [comment]
@ravindraguptacapgemini It's working fine in your fork code?

**Comment by ravindraguptacapgemini** [comment]
Yes, @danish5454 can try it once. 
@pushpender-singh-ap  created a PR for your review https://github.com/pushpender-singh-ap/react-native-scanner/pull/33

**Comment by pushpender-singh-ap** [comment]
@ravindraguptacapgemini Thank you for the PR. Please allow me to review the PR once I have thoroughly examined it. Upon completion of my review, I will release the beta version.

**Comment by ravindraguptacapgemini** [comment]
No @pushpender-singh-ap , as per my research OS is killing the camera when you are not scanning (but camera session is active in background) and on different screen, so when you come back it does not work.

**Comment by pushpender-singh-ap** [comment]
@ravindraguptacapgemini in this case RN hold the session but native clear the camera from there side after inactive, and in this case we need to register new session and clear the older one so camera again start for scanning. #33 in this PR you resolved this issue i am right?

**Comment by ravindraguptacapgemini** [comment]
@pushpender-singh-ap  yes

**Comment by ravindraguptacapgemini** [comment]
one have to call pausePreview so that preview layer won't continue scanning in background, and call resumePreview once back on the same page.

**Comment by pushpender-singh-ap** [comment]
@ravindraguptacapgemini During my testing of your issue last Sunday, I did not identify any memory leaks in iOS caused by this library. However, I did not test this on Android, so I cannot guarantee its performance on that platform.

You can also test this by creating a fresh project or using the example provided in the library.

Here are the steps to follow:

1. Open the project in Xcode.
2. Click on the `Product` menu and select `Profile` or press `Command + I`.
3. Select the `Memory Leaks` option.

Please do not hesitate to contact me if you require any assistance.

**Comment by ravindraguptacapgemini** [comment]
@pushpender-singh-ap this I think is a memory leak, which I reported. It is just like same instance of native component is being used in React Native. If you add scanner on multiple pages, the init method (initWithFrame) gets called only once.

**Comment by pushpender-singh-ap** [comment]
@ravindraguptacapgemini If you have time can you please provide me the example repo so it's will help me to debug the memory leak issue.

**Comment by pushpender-singh-ap** [comment]
Hi @danish5454 - Could you please re-test the dependency using the latest version? Here is the guide for installing the latest version:

`npm i @pushpendersingh/react-native-scanner@1.3.0-beta.1`
or 
`yarn add @pushpendersingh/react-native-scanner@1.3.0-beta.1`

example you can copy and paste before install the react-native-permissions package too: 


import React, {useEffect, useRef, useState} from 'react';
import {
  Alert,
  Platform,
  Text,
  SafeAreaView,
  Button,
  View,
  StyleSheet,
} from 'react-native';

import {
  request,
  PERMISSIONS,
  openSettings,
  RESULTS,
} from 'react-native-permissions'; // For camera permission
import {
  Commands,
  ReactNativeScannerView,
} from '@pushpendersingh/react-native-scanner';

export default function App() {
  const scannerRef = useRef(null);
  const [isCameraPermissionGranted, setIsCameraPermissionGranted] =
    useState(false);
  const [isActive, setIsActive] = useState(true);
  const [scannedData, setScannedData] = useState(null);

  useEffect(() => {
    checkCameraPermission();
  }, []);

  const handleBarcodeScanned = event => {
    const {data, bounds, type} = event?.nativeEvent;
    setScannedData({data, bounds, type});
    console.log('Barcode scanned:', data, bounds, type);
  };

  // Pause the camera after barcode / QR code is scanned
  const pausePreview = () => {
    if (scannerRef?.current) {
      Commands.pausePreview(scannerRef?.current);
      console.log('Camera preview paused');
    }
  };

  // Resume the camera after barcode / QR code is scanned
  const resumePreview = () => {
    if (scannerRef?.current) {
      Commands.resumePreview(scannerRef?.current);
      console.log('Camera preview resumed');
    }
  };

  const checkCameraPermission = async () => {
    request(
      Platform.OS === 'ios'
        ? PERMISSIONS.IOS.CAMERA
        : PERMISSIONS.ANDROID.CAMERA,
    ).then(async (result: any) => {
      switch (result) {
        case RESULTS.UNAVAILABLE:
          // console.log('This feature is not available (on this device / in this context)');
          break;
        case RESULTS.DENIED:
          Alert.alert(
            'Permission Denied',
            'You need to grant camera permission first',
          );
          openSettings();
          break;
        case RESULTS.GRANTED:
          setIsCameraPermissionGranted(true);
          break;
        case RESULTS.BLOCKED:
          Alert.alert(
            'Permission Blocked',
            'You need to grant camera permission first',
          );
          openSettings();
          break;
      }
    });
  };

  if (isCameraPermissionGranted) {
    return (
      <SafeAreaView style={{flex: 1}}>
        {isActive && (
          <ReactNativeScannerView
            ref={scannerRef}
            style={styles.scanner}
            onQrScanned={handleBarcodeScanned}
            pauseAfterCapture={false} // Pause the scanner after barcode / QR code is scanned
            isActive={isActive}
          />
        )}

        <View style={styles.controls}>
          <Button title="Pause Preview" onPress={pausePreview} />
          <Button title="Resume Preview" onPress={resumePreview} />
          <Button title="Stop Scanner" onPress={() => setIsActive(false)} />
          <Button title="Restart Scanner" onPress={() => setIsActive(true)} />
        </View>

        {scannedData && (
          <View style={styles.result}>
            <Text style={styles.resultText}>
              Scanned Data: {scannedData?.data}
            </Text>
            <Text style={styles.resultText}>Type: {scannedData?.type}</Text>
            <Text style={styles.resultText}>
              Bounds: {JSON.stringify(scannedData?.bounds)}
            </Text>
          </View>
        )}
      </SafeAreaView>
    );
  } else {
    return (
      <Text style={{fontSize: 30, color: 'red'}}>
        You need to grant camera permission first
      </Text>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: '#fff',
  },
  scanner: {
    flex: 1,
  },
  controls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 10,
    flexWrap: 'wrap',
    gap: 8,
    marginHorizontal: 10,
  },
  result: {
    marginTop: 16,
    padding: 16,
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
  },
  resultText: {
    fontSize: 16,
    marginVertical: 4,
  },
});
