### ISSUE TITLE
Compile issue in iOS

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [pushpender-singh-ap/react-native-scanner#35]
### Current behaviour
Getting compile time error

### Expected behaviour
Fix code in iOS ReactNativeScannerView.mm

### How to reproduce?
Just compile for iOS

### Preview
<img width="1462" alt="Screenshot 2024-12-02 at 6 33 15 PM" src="https://github.com/user-attachments/assets/b9bcd285-9abe-4db5-920a-cf542a3f76b3">

### What have you tried so far?
Nothing

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 15.2
| android                        | 14
| react-native                | 0.76.3
| @pushpendersingh/react-native-scanner    | 1.3.0
| node                            | 18.20.0
| npm or yarn                | 1.3.0

**Comment by ravindraguptacapgemini** [comment]
@pushpender-singh-ap we can't give default value like this in implementation, may be you can do it initWithFrame or init method

**Comment by pushpender-singh-ap** [comment]
I was made this change but forgot to undo i was try to set the default value in iOS.
