### ISSUE TITLE
Add Feature to Draw a Green Box Around Detected Barcodes

### ISSUE THREAD

**Issue by fatihydev** [pushpender-singh-ap/react-native-scanner#37]
Hello,

Thank you for the amazing barcode scanner library! I have a feature request: Would it be possible to add functionality that draws a green box around detected barcodes during the scanning process? This would make it visually clear which barcode has been detected, similar to the example in the attached image.

I believe this feature could greatly enhance the usability and visual feedback of your library. Thank you for considering this!

Best regards,
![csm_barcode-01-large_b87eacd3b0](https://github.com/user-attachments/assets/7e9db830-a155-4501-acd5-f4c92d9793cb)

**Comment by pushpender-singh-ap** [comment]
Hi @fatihydev - This feature is now available in version 1.4.0. Please refer to the example for further details.
