### ISSUE TITLE
fatal error: 'react/renderer/components/RNReactNativeScannerViewSpec/ComponentDescriptors.h' file not found

### ISSUE THREAD

**Issue by luvnishCapgemini** [pushpender-singh-ap/react-native-scanner#6]
Hi @pushpender-singh-ap,
I enabled newArch and build project from Jenkins.  After compilation I am facing this error:

```
/Users/****/JenkinsAgentUsevol/workspace/es_mobilev2_react-native-scanner/native/node_modules/@pushpendersingh/react-native-scanner/ios/ReactNativeScannerView.mm:3:9: fatal error: 'react/renderer/components/RNReactNativeScannerViewSpec/ComponentDescriptors.h' file not found
#import <react/renderer/components/RNReactNativeScannerViewSpec/ComponentDescriptors.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Please suggest any workaround.

Using:
"react": "^18.2.0",
"react-native": "0.72.1",
"@pushpendersingh/react-native-scanner": "^1.0.1"

**Comment by pushpender-singh-ap** [comment]
@luvnishCapgemini Hey buddy, I don't know how to setup Jenkins with a react native application, so I would appreciate if you could share with me an article about it.

**Comment by luvnishCapgemini** [comment]
@pushpender-singh-ap 
You can read it as push start
https://medium.com/@iampravikant/ci-cd-pipeline-for-react-native-project-in-jenkins-from-bitbucket-396fa29f8dc5

**Comment by pushpender-singh-ap** [comment]
Due to my busy schedule, I currently lack the time to address these issues. If you discover any solutions, kindly submit a pull request. Thank you for your understanding.
