### ISSUE TITLE
-[Feature] Scan multiple QR codes in IOS

### ISSUE THREAD

**Issue by luvnishCapgemini** [pushpender-singh-ap/react-native-scanner#7]
Hi @pushpender-singh-ap 

When we have multiple QR codes in front of camera then it only returns one QR code data at a time. Any approach or solution it could return one json with multiple QR codes data?

**Comment by pushpender-singh-ap** [comment]
@luvnishCapgemini This dependency support single QR code at a time.

**Comment by luvnishCapgemini** [comment]
Hi @pushpender-singh-ap 
It wasn't scan multiple QR code at one time in iOS.
For eg: you have multiple QR code on a wall/screen then it only returns one QR code data.

I forked your code and modified some code which is workaround. 
I raised an PR. Please confirm these changes. https://github.com/pushpender-singh-ap/react-native-scanner/pull/8

Thanks

**Comment by pushpender-singh-ap** [comment]
@luvnishCapgemini Multiple QR code working in Android is fine?

**Comment by pushpender-singh-ap** [comment]
@luvnishCapgemini PR is merge so now I am closing this issue.
